about:
  icons:  # 不要把 icon 注释掉，否则无法覆盖配置
   - { class: 'iconfont icon-github-fill', link: 'https://github.com/Rena1ssanc3' }
  # - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }
  name: "Rena1ssanc3"
  intro: "灵魂躁动不安。"
navbar:
  blog_title: Rena1ssanc3's Blog
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '关于' }
dark_mode:
  enable: false
  default: light
index:
  slogan:
    enable: true
    text: ''
    api:
      enable: false